packages:
  - "packages/*"
  - "admin"
  - "web"
  - "worker"
  - "infra/aws-cdk"

minimumReleaseAge: 4320

overrides:
  proxy-addr@<2.0.8: ^2.0.8
  tar@<7.5.19: ^7.5.19
  protobufjs@>=7.0.0 <7.5.5: ^7.5.5
  tinypool@<2.1.2: ^2.1.2
